### ISSUE TITLE
Crash Report - Sky Odyssey

### ISSUE THREAD

**Issue by Boardy2219** [nzminecraftDOTcom/ModdedServers#10]
**Select only one of these options by filling in the [ ] with an x**
- [ ] I am playing on the NZNetwork Vanilla Minecraft server
- [x] I am playing on one of the NZMinecraft Modded Minecraft servers

## **Basic Information**

Minecraft username: Boardy2219
Server you were playing on:  Sky Odyssey
Dedicated RAM: 6GB
Total installed RAM: 12GB

- [x] I have restarted my game fully and the problem still persists
- [ ] I have restarted my game fully and the problem comes back after a while
- [ ] I have restarted my game fully and the problem no longer happens
- [x] I have logged out of the server then back into the server and the problem still persists
- [ ] I have logged out of the server then back into the server and the problem comes back after a while
- [ ] I have logged out of the server then back into the server and the problem no longer happens
- [ ] The problem occurs when someone else logs into the server (Provide more details below)
- [ ] I have asked other players if there is a solution to this problem before creating this report
- [ ] I am having a problem that is not related to any of these options and I will provide more information below

## **Your issue or help request**

Was placing vibrant capacitor banks with the diamond wand, was working correctly until i ran out of necessary capacitor banks to fill a full row which was when my game crashed. Now each time i log in and join the server my game crashes with the error
 _The game crashed whilst unexpected error
Error: java.lang.ClassCastException: net.minecraft.item.ItemAir cannot be cast to crazypants.enderio.base.power.forge.item.IInternalPoweredItem_

## **Log files**

https://pastebin.com/aqev5nXv

**Comment by nzminecraftDOTcom** [comment]
What sky odyssey server

**Comment by Boardy2219** [comment]
It is the original server, sorry for not mentioning that

**Comment by nzminecraftDOTcom** [comment]
I've removed the cap banks and you should be ok to get on now
