### ISSUE TITLE
[Bug report] I have no title, please give me one!

### ISSUE THREAD

**Issue by Etcheberri** [nzminecraftDOTcom/ModdedServers#11]
**Select only one of these options by filling in the [ ] with an x**
- [ ] I am playing on the NZNetwork Vanilla Minecraft server
- [X] I am playing on one of the NZMinecraft Modded Minecraft servers

## **Basic Information**

Minecraft username:Etcheberry
Server you were playing on:Sky Odyssyey basic server
Dedicated RAM:8
Total installed RAM:16

- [ ] I have restarted my game fully and the problem still persists
- [ ] I have restarted my game fully and the problem comes back after a while
- [ ] I have restarted my game fully and the problem no longer happens
- [ X] I have logged out of the server then back into the server and the problem still persists
- [ ] I have logged out of the server then back into the server and the problem comes back after a while
- [ ] I have logged out of the server then back into the server and the problem no longer happens
- [ ] The problem occurs when someone else logs into the server (Provide more details below)
- [ ] I have asked other players if there is a solution to this problem before creating this report
- [ ] I am having a problem that is not related to any of these options and I will provide more information below

## **Your issue or help request**

Every time i log in i see waiting for server on waila bubbles and i get disconnected after 30 seconds

**Comment by nzminecraftDOTcom** [comment]
Can you please re-clarify what server you are on, there is no sky odyssey basic server
