### ISSUE TITLE
[Bug report] Crashing the server by being in the nether, with 32 chunk distance view

### ISSUE THREAD

**Issue by XxQCFighterxX** [nzminecraftDOTcom/ModdedServers#12]
**Select only one of these options by filling in the [ ] with an x**
- [ ] I am playing on the NZNetwork Vanilla Minecraft server
- [x ] I am playing on one of the NZMinecraft Modded Minecraft servers

## **Basic Information**

Minecraft username: XxQCFighterxX
Server you were playing on: Odyssey Original
Dedicated RAM: 4.5GB
Total installed RAM:8GB

- [ ] I have restarted my game fully and the problem still persists
- [ ] I have restarted my game fully and the problem comes back after a while
- [ ] I have restarted my game fully and the problem no longer happens
- [ ] I have logged out of the server then back into the server and the problem still persists
- [ ] I have logged out of the server then back into the server and the problem comes back after a while
- [ ] I have logged out of the server then back into the server and the problem no longer happens
- [ ] The problem occurs when someone else logs into the server (Provide more details below)
- [ ] I have asked other players if there is a solution to this problem before creating this report
- [x ] I am having a problem that is not related to any of these options and I will provide more information below

## **Your issue or help request**

Simple: i am in the nether, and with 32 chunk seeing distance, i crashed the server.
then i tried with 12 chunks, the regular, crashed too.
so the issue isn't with my computer, but with my position in the nether.

**Comment by nzminecraftDOTcom** [comment]
Seems to be solved, however the max render on the server is 6~ so you won't see past that.
