### ISSUE TITLE
[Bug report] Player can't mine

### ISSUE THREAD

**Issue by cs1konobe** [nzminecraftDOTcom/ModdedServers#13]
**Select only one of these options by filling in the [ ] with an x**
- [ ] I am playing on the NZNetwork Vanilla Minecraft server
- [x] I am playing on one of the NZMinecraft Modded Minecraft servers

## **Basic Information**

Minecraft username: Cs1konobe
Server you were playing on: Rougelike Adventures and Dungeons
Dedicated RAM: 3 GB
Total installed RAM: 4 GB

- [ x] I have restarted my game fully and the problem still persists
- [ ] I have restarted my game fully and the problem comes back after a while
- [ ] I have restarted my game fully and the problem no longer happens
- [ x] I have logged out of the server then back into the server and the problem still persists
- [ ] I have logged out of the server then back into the server and the problem comes back after a while
- [ ] I have logged out of the server then back into the server and the problem no longer happens
- [ ] The problem occurs when someone else logs into the server (Provide more details below)
- [ x] I have asked other players if there is a solution to this problem before creating this report
- [ ] I am having a problem that is not related to any of these options and I will provide more information below

## **Your issue or help request**

My character is unable to mine any blocks and I am unable to do anymore than 1 damage to mobs

**Comment by nzminecraftDOTcom** [comment]
What does the difficulty bar show in the area you are in.
Have you tried other tools/weapons from other mods

**Comment by cs1konobe** [comment]
My difficulty is 4 in my area, any weapon or tool besides a bow does only 1 damage
This problem occurs in other dimensions like the Twilight Forest

**Comment by cs1konobe** [comment]
Issue was caused by an enchantment on an armor piece
