### ISSUE TITLE
[Bug report] we cant connect on our island

### ISSUE THREAD

**Issue by clemhero** [nzminecraftDOTcom/ModdedServers#14]
**Select only one of these options by filling in the [ ] with an x**
- [ ] I am playing on the NZNetwork Vanilla Minecraft server
- [x ] I am playing on one of the NZMinecraft Modded Minecraft servers

## **Basic Information**

Minecraft username:clemhero
Server you were playing on:odyssey1
Dedicated RAM:8gb
Total installed RAM:16gb

- [x ] I have restarted my game fully and the problem still persists
- [ ] I have restarted my game fully and the problem comes back after a while
- [ ] I have restarted my game fully and the problem no longer happens
- [ x] I have logged out of the server then back into the server and the problem still persists
- [ ] I have logged out of the server then back into the server and the problem comes back after a while
- [ ] I have logged out of the server then back into the server and the problem no longer happens
- [ ] The problem occurs when someone else logs into the server (Provide more details below)
- [ x] I have asked other players if there is a solution to this problem before creating this report
- [ x] I am having a problem that is not related to any of these options and I will provide more information below

## **Your issue or help request**

when i connect on my island server show wait for server and  disconnect me i cant move and do nothing

**Comment by nzminecraftDOTcom** [comment]
What's the disconnection message.

**Comment by clemhero** [comment]
just disconnect server

**Comment by clemhero** [comment]
> What's the disconnection message.
connection lost 
disconneted
