### ISSUE TITLE
[Bug report]Recipes aren't working for EZStorage2

### ISSUE THREAD

**Issue by Killwish80** [nzminecraftDOTcom/ModdedServers#16]
**Select only one of these options by filling in the [ ] with an x**
- [ ] I am playing on the NZNetwork Vanilla Minecraft server
- [x ] I am playing on one of the NZMinecraft Modded Minecraft servers

## **Basic Information**

Minecraft username: Killwish80
Server you were playing on: RLA
Dedicated RAM: 8
Total installed RAM: 16

- [x ] I have restarted my game fully and the problem still persists

- [ x] I have logged out of the server then back into the server and the problem still persists

## **Your issue or help request**

Trying to craft items from EZStorage2 but the recipes aren't working for what they are said to be.

**Comment by nzminecraftDOTcom** [comment]
Game is as it comes from the developer, this is not something I can change.
