### ISSUE TITLE
[Bug report] Discord link has expired

### ISSUE THREAD

**Issue by sorifiend** [nzminecraftDOTcom/ModdedServers#18]
Server: NZnetwork

Hi buddy, just in case you hadn't noticed, the discord link in the [wiki](https://github.com/nzminecraftDOTcom/Minecraft/wiki) and on the server `/help` command message has expired. Can you swap it over to the newer link.

Existing expired link:
https://discordapp.com/invite/YnDH33U

New working link:
https://discordapp.com/invite/a3X5zAt

Cheers

**Comment by nzminecraftDOTcom** [comment]
Fixed, forgot to close this a long time ago though!
