### ISSUE TITLE
Stuck in loading screen

### ISSUE THREAD

**Issue by Shadey56** [nzminecraftDOTcom/ModdedServers#2]
Server:Sky Fac 4 classic
IGN: Shadey56
Dedicated RAM:9g
Total installed RAM:12g

- [ x] I have restarted my game fully and the problem still persists
- [x] I have restarted my game fully and the problem comes back after a while
- [ ] I have restarted my game fully and the problem no longer happens
- [x ] I have logged out of the server then back into the server and the problem still persists
- [ ] I have logged out of the server then back into the server and the problem comes back after a while
- [ ] I have logged out of the server then back into the server and the problem no longer happens
- [ ] The problem occurs when someone else logs into the server (Provide more details below)
- [ ] I have asked other players if there is a solution to this problem before creating this report
- [x ] I am having a problem that is not related to any of these options and I will provide more information below
Im stuck in a loading screen because the server restarted when i was in the twilight
## **Your issue or help request**

I'm stuck in the twilight loading screen.. plz send to spawn

**Comment by nzminecraftDOTcom** [comment]
Sent to spawn
