### ISSUE TITLE
server crashes when i join (my base)

### ISSUE THREAD

**Issue by Shadey56** [nzminecraftDOTcom/ModdedServers#3]
Sky factory4 classic
Minecraft username:Shadey56
Dedicated RAM:9g
Total installed RAM:12g
- [x ] I have restarted my game fully and the problem still persists
- [ ] I have restarted my game fully and the problem comes back after a while
- [ ] I have restarted my game fully and the problem no longer happens
- [ x] I have logged out of the server then back into the server and the problem still persists
- [ ] I have logged out of the server then back into the server and the problem comes back after a while
- [ ] I have logged out of the server then back into the server and the problem no longer happens
- [ ] The problem occurs when someone else logs into the server (Provide more details below)
- [ ] I have asked other players if there is a solution to this problem before creating this report
- [ x] I am having a problem that is not related to any of these options and I will provide more information below

## **Your issue or help request**

Whenever i join the server at my base the server starts lagging alot then it crashes

**Comment by Shadey56** [comment]
fixed

**Comment by Shadey56** [comment]
un fixed
plz help

**Comment by nzminecraftDOTcom** [comment]
I have removed things that are running and should nto be left running while offline.

**Comment by Shadey56** [comment]
fixed again i think
