### ISSUE TITLE
[Bug report] server crashes when I join the classic server

### ISSUE THREAD

**Issue by Lplayer04** [nzminecraftDOTcom/ModdedServers#4]
**Select only one of these options by filling in the [ ] with an x**
- [ ] I am playing on the NZNetwork Vanilla Minecraft server
- [x] I am playing on one of the NZMinecraft Modded Minecraft servers

## **Basic Information**

Minecraft username: lplayer04
Server you were playing on: Skyfactory 4 Version 4.0.3 NZminecraft Servers
Dedicated RAM:
Total installed RAM:

- [x] I have restarted my game fully and the problem still persists
- [ ] I have restarted my game fully and the problem comes back after a while
- [ ] I have restarted my game fully and the problem no longer happens
- [x] I have logged out of the server then back into the server and the problem still persists
- [ ] I have logged out of the server then back into the server and the problem comes back after a while
- [ ] I have logged out of the server then back into the server and the problem no longer happens
- [ ] The problem occurs when someone else logs into the server (Provide more details below)
- [x] I have asked other players if there is a solution to this problem before creating this report
- [ ] I am having a problem that is not related to any of these options and I will provide more information below

## **Your issue or help request**

I can join the Server hub, but everytime I want to join classic server the Server crashes

**Comment by nzminecraftDOTcom** [comment]
Your base has nothing at it, I don't see what would cause you to be crashing the server, it may just be coincidence.

**Comment by Lplayer04** [comment]
Thanks for your quick answer.
But what can I do against it?
