### ISSUE TITLE
Stuck loading into server

### ISSUE THREAD

**Issue by Etheria137** [nzminecraftDOTcom/ModdedServers#5]
- [x] I am playing on Minecraft modded Server

## **Basic Information**
Minecraft username: Etheria137
Server you were playing on: Sky Factory 4 Classic
Dedicated RAM: 7 GB
Total installed RAM: 16 GB

- [x] I have restarted my game fully and the problem still persists 
- [ ] I have restarted my game fully and the problem comes back after a while
- [ ] I have restarted my game fully and the problem no longer happens
- [ ] I have logged out of the server then back into the server and the problem still persists
- [ ] I have logged out of the server then back into the server and the problem comes back after a while
- [ ] I have logged out of the server then back into the server and the problem no longer happens
- [ ] The problem occurs when someone else logs into the server (Provide more details below)
- [ ] I have asked other players if there is a solution to this problem before creating this report
- [ ] I am having a problem that is not related to any of these options and I will provide more information below

## **Your issue or help request**
When I logged off the other day, I did so in the Twilight Forest. When I tried to log on today its stuck on the loading screen that says "Whisking you off to the twilight forest"
I just need someone to TP me to spawn.

## **Screenshots** 
https://imgur.com/a/trkJVII

**Comment by nzminecraftDOTcom** [comment]
I have sent you to spawn, next time you log in you should be there.
