### ISSUE TITLE
[Bug report] I have no title, please give me one!

### ISSUE THREAD

**Issue by omgty600** [nzminecraftDOTcom/ModdedServers#6]
**Select only one of these options by filling in the [ ] with an x**
- [ ] I am playing on the NZNetwork Vanilla Minecraft server
- [x ] I am playing on one of the NZMinecraft Modded Minecraft servers

## **Basic Information**

Minecraft username: omgty600
Server you were playing on: Skyfactory 4, Classic
Dedicated RAM: 8GB
Total installed RAM: 16GB

- [x ] I have restarted my game fully and the problem still persists
- [ ] I have restarted my game fully and the problem comes back after a while
- [ ] I have restarted my game fully and the problem no longer happens
- [ ] I have logged out of the server then back into the server and the problem still persists
- [ ] I have logged out of the server then back into the server and the problem comes back after a while
- [ ] I have logged out of the server then back into the server and the problem no longer happens
- [ ] The problem occurs when someone else logs into the server (Provide more details below)
- [ ] I have asked other players if there is a solution to this problem before creating this report
- [ ] I am having a problem that is not related to any of these options and I will provide more information below

## **Your issue or help request**

I am stuck in the twilight forest loading screen. Even when I relog and restart the minecraft client, the problem still persists.

**Comment by nzminecraftDOTcom** [comment]
You have been sent to spawn and should appear there on next login
