### ISSUE TITLE
[Bug report] Game crash upon logging in

### ISSUE THREAD

**Issue by omgty600** [nzminecraftDOTcom/ModdedServers#7]
**Select only one of these options by filling in the [ ] with an x**
- [ ] I am playing on the NZNetwork Vanilla Minecraft server
- [x] I am playing on one of the NZMinecraft Modded Minecraft servers

## **Basic Information**

Minecraft username: omgty600
Server you were playing on: Skyfactory 4, Classic
Dedicated RAM: 8GB
Total installed RAM: 16GB

- [x] I have restarted my game fully and the problem still persists
- [ ] I have restarted my game fully and the problem comes back after a while
- [ ] I have restarted my game fully and the problem no longer happens
- [ ] I have logged out of the server then back into the server and the problem still persists
- [ ] I have logged out of the server then back into the server and the problem comes back after a while
- [ ] I have logged out of the server then back into the server and the problem no longer happens
- [ ] The problem occurs when someone else logs into the server (Provide more details below)
- [ ] I have asked other players if there is a solution to this problem before creating this report
- [ ] I am having a problem that is not related to any of these options and I will provide more information below

## **Your issue or help request**

Upon logging in I get a "Ticking block entity" crash. I placed a brewing station down before and tried to insert a water bottle, but it crashed the game. Now whenever I log on, I get the same crash. Could you help me break the brewing station?

## **Log files**

https://pastebin.com/KCkJGtbN

**Comment by nzminecraftDOTcom** [comment]
Should be a block of glass next time you log in instead of the broken block.
