### ISSUE TITLE
Server crash on login (Odyssey2)

### ISSUE THREAD

**Issue by quin2k** [nzminecraftDOTcom/ModdedServers#8]
**Select only one of these options by filling in the [ ] with an x**
- [ ] I am playing on the NZNetwork Vanilla Minecraft server
- [X] I am playing on one of the NZMinecraft Modded Minecraft servers

## **Basic Information**

Minecraft username:  Quin2k
Server you were playing on:  Sky Odyssey 2
Dedicated RAM:  6k
Total installed RAM:  8k

- [X] I have restarted my game fully and the problem still persists
- [ ] I have restarted my game fully and the problem comes back after a while
- [ ] I have restarted my game fully and the problem no longer happens
- [X] I have logged out of the server then back into the server and the problem still persists
- [ ] I have logged out of the server then back into the server and the problem comes back after a while
- [ ] I have logged out of the server then back into the server and the problem no longer happens
- [ ] The problem occurs when someone else logs into the server (Provide more details below)
- [ ] I have asked other players if there is a solution to this problem before creating this report
- [ ] I am having a problem that is not related to any of these options and I will provide more information below

## **Your issue or help request**

Server has been crashing at login this morning.  Yesterday I had lag so bad that I couldn't even turn or interact with anything - it would go away when I went to the /spawn, so it seems specific to my base.  After a while it went away and I was able to play fine, but after I logged out and tried to return I get timed out when I log in and the server restarts shortly after.

The only thing I can think of is that before this started happening I put in some growth accelerators we'd received as a random quest reward.  The reward gave us 64 and I made a few more to fill in the gaps.  The only other automated stuff on the base are itemducts and servos/retrievers (since hoppers were banned).

## **Log files**

I didn't crash; your server logs probably have more details.

**Comment by nzminecraftDOTcom** [comment]
Do you have something that drops items on the ground by any chance?

**Comment by quin2k** [comment]
I do have some open crates that drop coal, but I have pressure plates underneath meant to prevent them from dropping more than a few at a time.  I was planning to upgrade to a different flower, but I was still missing some key ingredients for some of the runes (i.e. sugar cane).

**Comment by nzminecraftDOTcom** [comment]
machines removed that were causing the issue.
