### ISSUE TITLE
[Addition] Please give me a SkyFactory4 lostcity server w/prestige.

### ISSUE THREAD

**Issue by MikaelDrake** [nzminecraftDOTcom/ModdedServers#9]
**What server is this for**
- [ ] The NZnetwork Vanilla Minecraft servers
- [x ] One of the Forge Modpack servers

**Your suggestion**
- [ ] I have an idea for the server e.g minigame or game type
- [ ] I would like a new server for a modpack that has just been released
- [x ] I would like a new server for a modpack that has been out for a while
- [ ] I would like you to re-open a server for a modpack you have hosted before
- [ ] I would like you to change a configuration file to solve an issue in game
- [ ] I would like you to add a new plugin to the server

**Comment by nzminecraftDOTcom** [comment]
Best to ask this one in the server requests and suggestions channel, if enough people want it i can put it up.
